CREATE TABLE IF NOT EXISTS clientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  telefone VARCHAR(255),
  regiao VARCHAR(50) NOT NULL,
  idade INTEGER NOT NULL,
  canal_compra VARCHAR(50) NOT NULL,
  forma_pagamento VARCHAR(50) NOT NULL,
  modelo_veiculo VARCHAR(50) NOT NULL,
  data_compra DATE NOT NULL,
  historico_marca VARCHAR(20) NOT NULL,
  criado_em TIMESTAMP,
  atualizado_em TIMESTAMP
);

CREATE TABLE IF NOT EXISTS predicoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id BIGINT NOT NULL,
  perfil_previsto VARCHAR(30) NOT NULL,
  prob_fiel DECIMAL(5,4) NOT NULL,
  prob_abandono DECIMAL(5,4) NOT NULL,
  prob_esquecido DECIMAL(5,4) NOT NULL,
  prob_economico DECIMAL(5,4) NOT NULL,
  acao_sugerida CLOB,
  score_risco INTEGER NOT NULL,
  data_predicao TIMESTAMP,
  CONSTRAINT fk_predicao_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_predicoes_risco ON predicoes (score_risco);
